services:
  backend:
    build: ./services/backend
    ports:
      - "5000:5000"
    volumes:
      - ./services/backend:/app
    networks:
        - main
    container_name: uh_transcript_parser_backend

  frontend:
    build: ./services/frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
        - main
    container_name: uh_transcript_parser_frontend
networks:
  main:
